version: '3.8'

services:
  node-template:
    image: harbor.internal.codebuckets.in/node-template/node-template
    restart: unless-stopped
    ports:
      - "25000:3000"
    networks:
      - node_template_network
    env_file:
      - /home/empty.env

networks:
  node_template_network:
